### PR TITLE
Telnet

### PR DESCRIPTION
**Pull request by dleonard0**
Some type fixes.

### CODE REVIEW

**Comment by npat-efault** [comment]
Do any of these fix actual warnings? If so so, which warnings?

**Comment by npat-efault** [comment]
Thanks for the PR

Const corrections, merged

Enums, see 6d8bf34e9fb951f918a629ffbf55968eb1a569a9
(_briefly:_ defined `FC_ERROR` and `P_ERROR`,  both = -1. This way enums are forced to be signed, and the interface of the functions does not change---you can still check for < 0, if you wish. For me this is the best compromise...)

**Comment by dleonard0** [comment]
Hi!

They were clang warnings, seen in-editor. I don't recall the exact warnings, just showed up as red :)

Re enums, I think it's a matter of how you want to understand the underlying types (parity and flow control modes), as being unordered elements of a set or as indicies into a table. I am used to using enums for the former, which is why the `-1` looked strange to me.

**Comment by dleonard0** [comment]
Actually, there is a problem with -1 as a error value.
When (for example) `term_get_parity()` is called, it may return -1 to `show_status()` which uses the value as an index into `parity_str[]`, which is undefined. You could add a `<0` check in there, but I think it's safer to just not use -1.

**Comment by dleonard0** [comment]
If you're still open to persuasion on this:
https://github.com/dleonard0/picocom/commit/dfc412b9eca7fd693d79acf3e5ea430ef2ed9a7b
https://github.com/dleonard0/picocom/commit/489be68483a099a8758de1dcd2fd51a8bfe38820

**Comment by npat-efault** [comment]
These functions (`term_get_flowcntrl` and `term_get_parity`) can only fail if called with an `fd` that is not in the `term.[ch]` framework. That is, in almost all the cases, they are called in contexts where the caller *knows* they **cannot** fail. This is true for `show_status()`, and `do_command()`; which is why they don't check the return-value for < 0. 

As for the rest, I'm not leaning very strongly either way (that is, each solutions has its own ugliness). Since I don't wan't to spend too much time arguing or thinking about this I decided to go your way---mostly because it appears to be the least surprising at first glance.

See commit:  a412f6583a70a4e8cd8c0cf9221a2778dfbf6ce4

**Pull request closed without merging**
