### PR TITLE
Tiny whitespace cleanup

### PR DESCRIPTION
**Pull request by Joe-Merten**
I'd observed that you obviously prefer tabs for indentation. But some of your sources has mixed indentation (tabs and spaces). → picocom.c, term.h, term.c. This looks a bit ugly, when using a viewer / editor with different tab width setting. E.g. github shows sources with tab width of 8.

I'd also removed trailing whitespace in some sources.

### CODE REVIEW

**Comment by Joe-Merten** [comment]
Hmm, seems that I'm too noob in github PR. Only the first 2 commits should be assigned for this whitespace PR. The 3rd commit [03e6dc7](https://github.com/npat-efault/picocom/commit/03e6dc7db6f69af0c8446e0d034ecd3ae1eaf371) is regarding to PR #47. Sorry about this.

**Comment by npat-efault** [comment]
Please don't do this. Set tab-width to 4 on your editor , and the source will appear ok. I may someday untabify (spaces instead of tabs) the source, but leave it as is for now. 

Also: Added `.editorconfig` file which makes github render the sources with the correct tab-width. The `.editorconfig` file may also be honored by your editor. See: http://editorconfig.org/

**Comment by npat-efault** [comment]
Please resubmit the `--lower-rts` and `--lower-dtr` code as PR #47 or as a new PR.

**Comment by Joe-Merten** [comment]
If you like, then I'll be happy to provide you the detabbing as PR.

**Pull request closed without merging**
