### PR TITLE
Custom baudrate: small simplification in makefile and BSD implementation (like OSX)

### PR DESCRIPTION
**Pull request by Joe-Merten**
see also https://github.com/npat-efault/picocom/pull/42

### CODE REVIEW

**Comment by Joe-Merten** [comment]
I'll think about a solution which is able to allow automatically enabling custom baud rate for all platforms which has an corresponding implementation in `term.c`.

**Comment by npat-efault** [comment]
I do not consider automatically enabling custom-baud support very important. Custom baud support is a marginal feature, anyhow, since it cannot be implemented in a portable manner across systems. If somebody needs it, he can enable it by commenting-in a line in the Makefile (no big deal). That's more than good enough for me, and much better than including a maze of ifdef's that are hard to test on all systems.

**Comment by npat-efault** [comment]
Also, this should be two PRs, not one. The first, reg. the Makefile, I would merge. The second (custom-baud for BSDs) not until I have some verification that it actually works on these systems.

**Comment by Joe-Merten** [comment]
Regarding BSD: I'll work on it after fixed OSX custom baud rate issue.

**Pull request closed without merging**
