### PR TITLE
Suggestion to fix osx custom baudrate issue #57

### PR DESCRIPTION
**Pull request by Joe-Merten**
see also https://github.com/npat-efault/picocom/issues/57

Test conditions:
- OSX El Capitan 10.11.6
- Driver FTDIUSBSerialDriver_v2_3.dmg
- US232R-10 adapter (http://www.ftdichip.com/Products/Cables/USBRS232.htm)

I'm not really happy with this approach, hacking into `term_apply()`. Might have an idea for a cleaner way?

### CODE REVIEW

**Comment by npat-efault** [comment]
I don't like it either... 

I would suggest moving the `c{set|get}{i|o}speed_custom()` implementations in a separate file `custbaud_osx.[ch]` (analogous to `termios2.[ch]`) and overriding the implementation of `tc{set|get}attr()`, again in a manner similar to `termios2.c`.

What do you think?

**Comment by npat-efault** [comment]
This way the only changes in `term.[ch]` will be the inclusion of `custbaud_osx.h` if building for OSX

**Comment by Joe-Merten** [comment]
Ok, I'll give it a try.

**Comment by Joe-Merten** [comment]
Hmm, doing this way, the workaround will also be executed for all other calls of `tcsetattr()`, e.g. in `term_exitfunc()`, `term_lib_init()`, `term_remove()`, `term_replace` and `term_reset()`.

**Comment by npat-efault** [comment]
Yes, why shouldn't it?

**Comment by npat-efault** [comment]
I mean if the port was set to a custom br before starting picocom, it should be reset to that custom br after exiting!

**Comment by npat-efault** [comment]
If on the other hand the port was set to a std baudrate before starting picocom, then the "patched" tcsetattr should behave identically with the std tcsetattr

**Comment by npat-efault** [comment]
Of course it must be tested thoroughly...

**Comment by Joe-Merten** [comment]
Yep, I even think that's more correct this way.
Having a working patch now. Unfortunately, lost access to `Bcode()`, so I cannot check if it is standard baudrate. `term_baud_ok()` cannot used for this. Might add a `term_is_std_baud()`?
```
int term_is_std_baud(int baud) {
    return (Bcode(baud) != BNONE) ? 1 : 0;
}
```

**Comment by Joe-Merten** [comment]
Or otherwise, I'll just remove this check and apply the code independent of the baudrate. It will also work.

**Comment by npat-efault** [comment]
Sure, just name it `term_baud_std()` to be similar with `term_baud_ok()`

**Comment by Joe-Merten** [comment]
... would be nice to do the whitespace job next time (tabs, trailing WS) - my editor (eclipse) is set by default to remove all trailing WS when save ...

**Comment by Joe-Merten** [comment]
Regarding your prefered coding style: Are line comments `//` ok or only `/* */` allowed in your project?

**Comment by npat-efault** [comment]
Only C-style (not C++-style comments): `/* ... */`

**Comment by npat-efault** [comment]
Also added issue for WS cleanup. If you can provide a PR that untabifies everything and removes trailing WS (without affecting formatting) it would be great. **It should be a separate PR by itself**.

**Pull request closed without merging**
