### PR TITLE
Automatically enable custom baud rate support on Linux > 2.6

### PR DESCRIPTION
**Pull request by SimGer**
This is a suggestion for issue #38

### CODE REVIEW

**Comment by npat-efault** [comment]
Thanks for the patch! I want to keep the Makefile clean and simple, without much GNU-Make-isms. Because of this I will not merge the request. One can always comment-in a couple of lines and rebuld. If a package is made for a specific distro it can include these changes...

**Comment by Joe-Merten** [comment]
Might consider this approach?
→ https://github.com/Joe-Merten/picocom/commit/94e613aeef17223b1b60c6e934aa1e032b7777a7
This enables custom baud rate support by default for Linux and OSX and keeps the Makefile clean from OS dependencies.
We could add a kernel version check on preprocessor level as described [here](http://stackoverflow.com/a/16721774/2880699).
I could provide a PR for this.

**Comment by npat-efault** [comment]
Yes, I like the cleaner Makefile! I don't like enabling custom-baudrate support by default (it might *not* work for all architectures, and I have no way to test / make sure). 

So I'm ok having **only** to define the `USE_CUSTOM_BAUD` macro to get the respective functionality, for architectures that support it (i.e. without having to comment-in the `OBJS1 +=` stuff). But, by default, the USE_HIGH_BAUD option should be disabled. 

The packager for a specific OS / arch / distro can choose to enable or leave disabled the option when making a binary package. If someone installs from source, he *should* take a look at the Makefile and enable the desired options.

So yes, please submit the PR that simplifies the mechanism, but by default `USE_CUSTOM_BAUD` should be disabled in the Makefile.

**Comment by npat-efault** [comment]
Also as the code is, at the moment, if you enable USE_CUSTOM_BAUD for an OS othen than Linux / OSX, picocom will not compile.

**Comment by Joe-Merten** [comment]
I'd checked the baudrate constants in termios.h of FreeBsd and OpenBsd and they looking very similar to those of OSX:
- https://github.com/freebsd/freebsd/blob/master/sys/sys/_termios.h
- https://github.com/openbsd/src/blob/5271000b44abe23907b73bbb3aa38ddf4a0bce08/sys/sys/termios.h

Assuming, that Bsd, NetBsd and Dragonfly going the same way, it seems simple to fix the BSD builds with `#define USE_CUSTOM_BAUD` by just changing term.c:213 from:
`    #if defined(__APPLE__) && defined (USE_CUSTOM_BAUD)`
to something like:
`    #if defined (USE_CUSTOM_BAUD) && (defined(__APPLE__) || defined(__FreeBSD__) || ... )`

**Comment by npat-efault** [comment]
I know they are similar, and it would probably work, but have you actually tested it? I would not like to include support for something that is not tested. If somebody verifies that custom-baud actually works on a specific BSD (or other system) then I would gladly merge the respective PR.

**Comment by Joe-Merten** [comment]
I'd just installed FreeBsd as VirtualBox guest, but unfortunately failed to route USB into. I'll now install FreeBsd 11 native for testing.

**Pull request closed without merging**
